default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/shakapacker-cache
  extensions:
    - .js
    - .jsx
    - .json
    - .css
    - .scss
    - .sass
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg

development:
  <<: *default
  compile: true
  dev_server:
    https: false
    host: localhost
    port: 3035
    public: localhost:3035
    hmr: false

test:
  <<: *default
  compile: true

production:
  <<: *default
  compile: false
